#!/bin/bash
set -o errexit

# Renew all live certificates with LetsEncrypt.  This needs to run at least
# once every three months.
service apache2 stop
/root/letsencrypt/letsencrypt-auto renew -c /etc/letsencrypt/cli.conf
service apache2 start

# Services that rely on LE certificates may need restarted and/or other actions.
for script in $(find /etc/letsencrypt/postrenew/ -maxdepth 1 -type f -executable); do
  echo "Executing ${script}."
  $script
done
