#!/bin/bash
set -o errexit
# Renew all live certificates with LetsEncrypt.  This needs to run at least
# once every three months, but recommended frequency is once a day.

/root/letsencrypt/letsencrypt-auto renew --pre-hook="service apache2 stop" --post-hook="service apache2 start" \
    -c /etc/letsencrypt/cli.conf

# Services that rely on LE certificates may need restarted and/or other actions.
for script in $(find /etc/letsencrypt/postrenew/ -maxdepth 1 -type f -executable); do
  echo "Executing ${script}."
  $script
done
