## Generated by Roundcube Webmail SieveRules Plugin ##
require ["regex","fileinto","imap4flags"];

# rule:[Is spam]
if allof (header :regex "X-DSPAM-Result" "^(Spam|Virus|Bl[ao]cklisted)$",
	not header :contains "X-DSPAM-Reclassified" "Innocent")
{
	setflag "\\Seen";
	fileinto "Junk";
	stop;
}
